### ISSUE TITLE
Does storefront-qwik-starter work on latest vendure v2+.  

### ISSUE THREAD

**Issue by ivsaneesh** [vendure-ecommerce/storefront-qwik-starter#105]
When trying to run the apllication getting the error `[vite] Internal server error: fetch failed`

`[vite] Internal server error: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11457:11)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at process.processImmediate (node:internal/timers:447:9)
      at async executeRequest (C:\saneesh\projects\vendure\storefront-qwik-starter\src\utils\api.ts:51:23)
      at async execute (C:\saneesh\projects\vendure\storefront-qwik-starter\src\utils\api.ts:30:5)
      at async Module.getCollections (C:\saneesh\projects\vendure\storefront-qwik-starter\src\providers\collections\collections.ts:6:9)
      at async Object.useCollectionsLoader_routeLoader_7EpNZDTiNAI (C:\saneesh\projects\vendure\storefront-qwik-starter\src\routes\layout.tsx:23:9)
      at async Object.invokeQRL (C:\saneesh\projects\vendure\storefront-qwik-starter\dist-dev\tsc-out\packages\qwik\src\core\util\implicit_dollar.js:8177:24)
      at async measure (file:///C:/saneesh/projects/vendure/storefront-qwik-starter/node_modules/@builder.io/qwik-city/vite/index.mjs:24181:12)
`

**Comment by ivsaneesh** [comment]
> Hi, which version of node are you using?

Node version 18+

**Comment by gioboa** [comment]
I close this issue because it's stale
