### ISSUE TITLE
Problems with project setup

### ISSUE THREAD

**Issue by Evotros** [vendure-ecommerce/storefront-qwik-starter#147]
I get the following error when running `npm install`:
```
While resolving: storefront-qwik-starter@undefined
Found: eslint@8.45.0
node_modules/eslint
  dev eslint@"8.45.0" from the root project

Could not resolve dependency:
peer eslint@"^8.56.0" from eslint-plugin-qwik@1.4.0
node_modules/eslint-plugin-qwik
  dev eslint-plugin-qwik@"1.4.0" from the root project
``` 

> Fixed by setting the version to `8.56.0` in package.json

Next error is:
```
40 timing command:install Completed in 21ms
41 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
41 verbose stack     at unsupportedURLType (B:\ProgramData\nvm\v18.19.0\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:310:15)
41 verbose stack     at fromURL (B:\ProgramData\nvm\v18.19.0\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:367:13)
41 verbose stack     at Function.resolve (B:\ProgramData\nvm\v18.19.0\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:83:12)
41 verbose stack     at #nodeFromEdge (B:\ProgramData\nvm\v18.19.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1048:22)
41 verbose stack     at #buildDepStep (B:\ProgramData\nvm\v18.19.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:917:35)
41 verbose stack     at #buildDeps (B:\ProgramData\nvm\v18.19.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:769:30)
41 verbose stack     at Arborist.buildIdealTree (B:\ProgramData\nvm\v18.19.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:196:28)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (B:\ProgramData\nvm\v18.19.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
41 verbose stack     at async Install.exec (B:\ProgramData\nvm\v18.19.0\node_modules\npm\lib\commands\install.js:152:5)

```

This comment: https://stackoverflow.com/a/75174993 states that `pnpm` was the problem.
Do we have to use `pnpm`? I would like to have the README improved for the setup.

**Comment by gioboa** [comment]
Hi, I'm using `pnpm` and I think is the right way for this project too. Would you like to drop a PR to improve the README.md?

**Comment by gioboa** [comment]
Stale issue. I close it, thanks
