### ISSUE TITLE
Cannot access home page

### ISSUE THREAD

**Issue by yasserlens** [vendure-ecommerce/storefront-qwik-starter#92]
To reproduce:
- I used the most recent version as of 20 Apr 2023 (commit 64d043c)
- in the project main directory, I ran npm install
- then npm start

The main home page shows an error:
```
VITE v4.2.1  ready in 924 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
4:49:47 AM [vite] Error when evaluating SSR module /src/env.ts:

4:49:47 AM [vite] Error when evaluating SSR module /src/utils/index.ts:

4:49:47 AM [vite] Error when evaluating SSR module /src/utils/api.ts:

4:49:47 AM [vite] Error when evaluating SSR module /src/graphql-wrapper.ts:

4:49:47 AM [vite] Error when evaluating SSR module /src/providers/checkout/checkout.ts:

4:49:47 AM [vite] Error when evaluating SSR module /.../qwik+storefront/src/routes/layout.tsx:

4:49:47 AM [vite] Internal server error: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "VITE_SECURE_COOKIE"
    ],
    "message": "Required"
  }
]
  File: /.../qwik+storefront/node_modules/zod/lib/index.mjs:537:31
  535|                  if (this._error)
  536|                      return this._error;
  537|                  const error = new ZodError(ctx.common.issues);
     |                                 ^
  538|                  this._error = error;
  539|                  return this._error;
      at get error [as error] (file:///.../qwik+storefront/node_modules/zod/lib/index.mjs:537:31)
      at ZodObject.parse (file:///.../qwik+storefront/node_modules/zod/lib/index.mjs:636:22)
      at /.../qwik+storefront/src/env.ts:12:42
      at async instantiateModule (file:///.../qwik+storefront/node_modules/vite/dist/node/chunks/dep-79892de8.js:53996:9)
```

**Comment by gioboa** [comment]
Do you have VITE_SECURE_COOKIE in your .env file?

**Comment by yasserlens** [comment]
Sorry I missed that part in the errors log - thanks for catching it. Setting that env variable resolved the issue. It would help if you could add it there by default since there is no try..catch for it in place.

**Comment by gioboa** [comment]
The variable is present in the main branch
https://github.com/vendure-ecommerce/storefront-qwik-starter/blob/335bb896c9ad7b16f87f1dfeef3e088ce0acb448/.env#L5
